services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5600:5600"
    volumes:
      - ./:/home/node/.n8n
    environment:
      N8N_PORT: 5600
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_RESTRICT_FILE_ACCESS_TO: /files
    restart: unless-stopped
